version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - nvm use 20
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: dist
